run_name: kfold-ml-arnn
seed: 317

model:
  name: MLARNN
  params:
    rnn_type: LSTM
    rnn_units: 128
    rnn_num_layers: 1
    top_classifier_units: 32

optimizer:
  name: Adam
  params:
    lr: 0.0005
    weight_decay: 1e-05

scheduler:
  name: StepLR
  params:
    step_size: 20000
    gamma: 0.5

train_batch_size: 128
val_batch_size: 256
num_epochs: 15
device: cuda
path_to_checkpoints: "drive/MyDrive/ml/dl-alpha-competition/checkpoints/kfold-ml-alstm-attn/"
submission_filename: test_submission.csv

buckets_path: "/content/drive/MyDrive/ml/dl-alpha-competition/kfold-validation/"
test_buckets_path: "/content/drive/MyDrive/ml/dl-alpha-competition/time-series-validation/test_buckets_rnn"
uniques_emb_path: "/content/dl-fintech-alpha/data/processed/uniques.pkl"